[general]
birth = "21 April 2022"
address = "Bojongsoang, Bandung, Jawa Barat, 40288"
full_name = "Muhammad Afryan Saputra"
email = "afryan54@gmail.com"
phone = "(+62) 812-2006-1316"

[PATH_CONFIGURATION]
path_images = "assets/images/"
path_css = "assets/css/"
path_pdf = "assets/"